import { NextResponse } from "next/server";
import { connectDB } from "../../../../lib/db";
import { Job, Company } from "../../../../models";
import { requirePermission } from "../../../../lib/guard";
import { PERMISSIONS } from "../../../../lib/rbac";

export async function GET(_, { params }) { try { await connectDB(); const { id } = await params; const job = await Job.findByIdAndUpdate(id, { $inc: { views: 1 } }, { new: true }).populate("company", "name logo website industry headquarters"); if (!job) return NextResponse.json({ error: "Job not found." }, { status: 404 }); return NextResponse.json({ job }); } catch { return NextResponse.json({ error: "Job not found." }, { status: 404 }); } }
export async function PATCH(request, { params }) { const guard = await requirePermission(PERMISSIONS.manageOwnJobs, PERMISSIONS.moderateJobs); if (guard.error) return guard.error; try { await connectDB(); const { id } = await params; const job = await Job.findById(id).populate("company"); if (!job) return NextResponse.json({ error: "Job not found." }, { status: 404 }); if (guard.session.role !== "admin" && job.company.owner.toString() !== guard.session.userId) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); Object.assign(job, await request.json()); await job.save(); return NextResponse.json({ job }); } catch { return NextResponse.json({ error: "Unable to update job." }, { status: 400 }); } }
export async function DELETE(_, { params }) { const guard = await requirePermission(PERMISSIONS.manageOwnJobs, PERMISSIONS.moderateJobs); if (guard.error) return guard.error; try { await connectDB(); const { id } = await params; const job = await Job.findById(id).populate("company"); if (!job) return NextResponse.json({ error: "Job not found." }, { status: 404 }); if (guard.session.role !== "admin" && job.company.owner.toString() !== guard.session.userId) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); await job.deleteOne(); return NextResponse.json({ success: true }); } catch { return NextResponse.json({ error: "Unable to delete job." }, { status: 400 }); } }
